In [170]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd   
#Lấy dữ liệu từ user_data1.csv
df = pd.read_csv('user_data1.csv')
x = df.iloc[:, [1,2, 3]].values  
y = df.iloc[:, 4].values 
print(df.head()) 

   User ID  Gender  Age  EstimatedSalary  Purchased
0   765432    Male   19            19000          0
1   123456    Male   35            20000          0
2   132457  Female   26            43000          0
3   654321  Female   27            57000          0
4   134566    Male   19            76000          0


In [171]:
inputs = df.drop('Purchased',axis='columns')
target = df.Purchased

In [172]:
dummies = pd.get_dummies(inputs.Gender) #get_dummies tạo biến giả
dummies.head(3) #hiển thị 3 hàng đầu tiên của dummies

Female  Male
0       0     1
1       0     1
2       1     0

In [173]:
inputs = pd.concat([inputs,dummies],axis='columns') #concat() để kết hợp DataFrame inputs và dummies theo chiều cột (axis='columns'). 
inputs.head(3)

User ID  Gender  Age  EstimatedSalary  Female  Male
0   765432    Male   19            19000       0     1
1   123456    Male   35            20000       0     1
2   132457  Female   26            43000       1     0

In [174]:
#Bỏ cột Gender và Male
inputs.drop(['Gender','Male'],axis='columns',inplace=True)
inputs.head(3)

User ID  Age  EstimatedSalary  Female
0   765432   19            19000       0
1   123456   35            20000       0
2   132457   26            43000       1

In [175]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [176]:
inputs.Age[:10] #lấy ra 10 giá trị đầu tiên của cột Age trong inputs

0    19
1    35
2    26
3    27
4    19
5    27
6    27
7    32
8    25
9    35
Name: Age, dtype: int64

In [177]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)
#train_test_split chia tập dữ liệu thành tập huấn luyện và tập kiểm tra.
#xác định tỷ lệ của tập kiểm tra trong tổng số dữ liệu, 
# ở đây là 0.3 tức là tập kiểm tra chiếm 30% tổng số dữ liệu, tập huấn luyện sẽ chiếm 70% tổng số dữ liệu.
# Fitting Naive Bayes to the Training set  
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()


In [140]:
# Making the Confusion Matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)  

In [178]:
model.fit(X_train,y_train)

GaussianNB()

In [179]:
model.score(X_test,y_test)
#Phương thức fit() được gọi trên đối tượng model để huấn luyện mô hình trên tập dữ liệu huấn luyện X_train và y_train

0.7142857142857143

In [180]:
X_test[0:10]

User ID  Age  EstimatedSalary  Female
8    753356   25            33000       0
5    654323   27            58000       0
4    134566   19            76000       0
14   753362   18            82000       0
0    765432   19            19000       0
16   753364   47            25000       0
1    123456   35            20000       0

In [181]:
y_test[0:10]

8     0
5     0
4     0
14    0
0     0
16    1
1     0
Name: Purchased, dtype: int64

In [166]:
model.predict(X_test[0:10])

array([1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [184]:
#sẽ trả về một mảng 2 chiều chứa các xác suất dự đoán cho 10 mẫu đầu tiên trong tập dữ liệu kiểm tra X_test.
model.predict_proba(X_test[:10])

array([[2.45968336e-03, 9.97540317e-01],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [1.46125029e-02, 9.85387497e-01],
       [1.00000000e+00, 0.00000000e+00],
       [3.24259990e-07, 9.99999676e-01],
       [1.00000000e+00, 0.00000000e+00]])

In [183]:
#Tính điểm bằng xác thực chéo
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.66666667, 0.33333333, 0.33333333, 0.66666667, 0.66666667])